# Generated by Django 5.2.1 on 2025-05-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='pdfmessage',
            options={'verbose_name': 'PDF Message', 'verbose_name_plural': 'PDF Messages'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the appointment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the specialty.', null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(help_text='The name of the medical specialty.', max_length=100, unique=True),
        ),
    ]
