# Generated by Django 5.2.1 on 2025-05-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='reason',
            new_name='purpose',
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
