# Generated by Django 5.2.1 on 2025-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0003_remove_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('general_surgery', 'General Surgery'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('internal_medicine', 'Internal Medicine'), ('obstetrics_gynecology', 'Obstetrics and Gynecology'), ('urology', 'Urology'), ('gastroenterology', 'Gastroenterology'), ('endocrinology', 'Endocrinology'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('rheumatology', 'Rheumatology'), ('infectious_diseases', 'Infectious Diseases'), ('ophthalmology', 'Ophthalmology'), ('otolaryngology', 'Otolaryngology'), ('plastic_surgery', 'Plastic Surgery'), ('pathology', 'Pathology'), ('family_medicine', 'Family Medicine'), ('sports_medicine', 'Sports Medicine'), ('geriatrics', 'Geriatrics'), ('other', 'Other')], default='general_surgery', help_text='The medical specialty of the doctor.', max_length=100),
        ),
    ]
