# Generated by Django 5.2.1 on 2025-05-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
    ]
