# Generated by Django 5.2.1 on 2025-05-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Billing date.'),
        ),
    ]
